wrapperVersion=3.3.4
distributionType=zip
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.15/apache-maven-3.9.15-bin.zip
distributionBase=wrapper
distributionPath=.m2/wrapper/dists
zipStoreBase=wrapper
zipStorePath=.cache/wrapper
